version: '3.8'

services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - "5000:5000"
    environment:
      - FLASK_ENV=development
      - DATABASE_URL=postgresql://roomieflow:roomieflow@db:5432/roomieflow
      - JWT_SECRET_KEY=your-secret-key-change-in-production
    depends_on:
      - db
    volumes:
      - ./backend:/app
    command: flask run --host=0.0.0.0

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    volumes:
      - ./frontend:/app
      - /app/node_modules
    depends_on:
      - backend

  db:
    image: postgres:15
    environment:
      - POSTGRES_DB=roomieflow
      - POSTGRES_USER=roomieflow
      - POSTGRES_PASSWORD=roomieflow
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data: